# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    name: Build playlist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Playlist
        run: |
          mkdir dist
          python main.py

      - name: Release
        run: |
          set -x
          cd dist
          zip -r playlist_by_rating.zip ./*.csv
          assets=()
          for asset in ./*.json; do
            assets+=("-a" "$asset")
          done
          assets+=("-a" "playlist_by_rating.zip")
          tag_name=`date '+%Y%m%d%H%M'`
          hub release create "${assets[@]}" -m "Latest" "$tag_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup
        uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}