name: BUILD

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 18 * * *"
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:
    name: Build playlist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Playlist
        run: |
          mkdir dist
          python main.py

      - name: Release
        run: |
          set -x
          cd dist
          zip -r bad-rating-playlist.zip ./*.*
          assets=()
          for asset in ./*.csv; do
            assets+=("$asset")
          done
          for asset in ./*.json; do
            assets+=("$asset")
          done
          assets+=("-a" "bad-rating-playlist.zip")
          tag_name=`date '+%Y%m%d%H%M'`
          gh release create "$tag_name" "${assets[@]}" --latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup
        uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
